# Generated by Django 5.1.4 on 2025-01-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_rename_borrower_id_borrowingmodel_borrowing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowingmodel',
            old_name='borrwing_title',
            new_name='borrowing_title',
        ),
    ]
