# Generated by Django 5.1.4 on 2025-01-09 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_rename_borrwing_title_borrowingmodel_borrowing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingmodel',
            name='borrowing_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
