# Generated by Django 5.1.4 on 2025-01-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_borrowingmodel_borrowing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingmodel',
            name='borrowing_image',
        ),
    ]
