# Generated by Django 5.1.4 on 2025-01-10 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0005_remove_borrowingmodel_borrowing_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingmodel',
            name='borrowing_image',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='borrowingmodel',
            name='borrowing_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
