# Generated by Django 5.1.4 on 2025-01-10 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0006_borrowingmodel_borrowing_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingmodel',
            name='borrowing_id',
        ),
        migrations.AddField(
            model_name='borrowingmodel',
            name='borrower_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_borrower', to=settings.AUTH_USER_MODEL),
        ),
    ]
