# Generated by Django 5.1.4 on 2025-01-10 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0009_alter_borrowingmodel_borrower_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingmodel',
            name='borrower_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_borrower', to=settings.AUTH_USER_MODEL),
        ),
    ]
