# Generated by Django 5.1.4 on 2025-01-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0011_rename_borrower_user_id_borrowingmodel_borrwoing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingmodel',
            name='borrowing_image',
        ),
    ]
