# Generated by Django 5.1.4 on 2025-01-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0013_borrowingmodel_borrowing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowingmodel',
            old_name='borrwoing_id',
            new_name='borrowing_id',
        ),
    ]
