# Generated by Django 5.1.4 on 2025-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0019_borrowmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingmodel',
            name='borrowing_stock',
            field=models.IntegerField(default=50),
        ),
    ]
