# Generated by Django 5.1.4 on 2025-01-18 19:24

import borrowing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0020_borrowingmodel_borrowing_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='borrow_expiry',
            field=models.DateField(default=borrowing.models.test),
        ),
    ]
