# Generated by Django 5.1.4 on 2025-01-21 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0021_alter_borrowmodel_borrow_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorrowModel',
            new_name='RentModel',
        ),
    ]
