# Generated by Django 5.1.4 on 2025-01-21 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0022_rename_borrowmodel_rentmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentmodel',
            unique_together={('borrower', 'borrow_material')},
        ),
    ]
